<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>particle_filter</name>
  <version>0.1.0</version>
  <description>ROS 2 version of Particle Filter Localization using RangeLibc for accelerated ray casting.</description>

  <!-- One maintainer tag required, multiple allowed, one person per tag -->
  <maintainer email="hariharanr1799@gmail.com">Hariharan Ravichandran</maintainer>
  <author email="tialim@student.ethz.ch">Tianyi Lim</author>

  <!-- One license tag required, multiple allowed, one license per tag -->
  <license>MIT</license>

  <url type="website">https://arxiv.org/abs/2401.07658</url>

  <buildtool_depend>ament_python</buildtool_depend>
  
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>nav2_map_server</depend>
  <depend>tf_transformations</depend>
  
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
